"""empty message

Revision ID: a89df01c20eb
Revises: 
Create Date: 2019-03-01 18:52:32.627154

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a89df01c20eb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('db_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('md5', sa.String(length=128), nullable=True),
    sa.Column('completed', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cardstocollections',
    sa.Column('card_id', sa.Integer(), nullable=True),
    sa.Column('collection_id', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['card_id'], ['card.id'], ),
    sa.ForeignKeyConstraint(['collection_id'], ['collection.id'], )
    )
    op.add_column('cardstomainboard', sa.Column('quantity', sa.Integer(), nullable=True))
    op.add_column('cardstosideboard', sa.Column('quantity', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cardstosideboard', 'quantity')
    op.drop_column('cardstomainboard', 'quantity')
    op.drop_table('cardstocollections')
    op.drop_table('db_info')
    # ### end Alembic commands ###
